#!/bin/bash
#SBATCH -J SEACR
#SBATCH -p general
#SBATCH -e cJun_SEACR_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=xuexiao@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=40:00:00

module unload python
module load python
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
source activate velocyto

# Make sure all bam files have index!!!
cd /N/slate/xuexiao/cJun_CREB1_ChIP/Align

samtools index Ctrl_H3K9_S26_marked_duplicates.bam Ctrl_H3K9_S26_marked_duplicates.bai
samtools index OV33D_Input_S25_marked_duplicates.bam OV33D_Input_S25_marked_duplicates.bai
samtools index OV33D_IgG_S24_marked_duplicates.bam OV33D_IgG_S24_marked_duplicates.bai
samtools index OV33D_cJun_S23_marked_duplicates.bam OV33D_cJun_S23_marked_duplicates.bai
samtools index OV3Ctrl_Input_S22_marked_duplicates.bam OV3Ctrl_Input_S22_marked_duplicates.bai
samtools index OV3Ctrl_IgG_S21_marked_duplicates.bam OV3Ctrl_IgG_S21_marked_duplicates.bai
samtools index OV3Ctrl_cJun_S20_marked_duplicates.bam OV3Ctrl_cJun_S20_marked_duplicates.bai
samtools index OV3Ctrl_H3K9_S19_marked_duplicates.bam OV3Ctrl_H3K9_S19_marked_duplicates.bai
samtools index Kura3D_Input_S18_marked_duplicates.bam Kura3D_Input_S18_marked_duplicates.bai
samtools index Kura3D_IgG_S17_marked_duplicates.bam Kura3D_IgG_S17_marked_duplicates.bai
samtools index Kura3D_cJun_S16_marked_duplicates.bam Kura3D_cJun_S16_marked_duplicates.bai
samtools index Kura3D_H3K9_S15_marked_duplicates.bam Kura3D_H3K9_S15_marked_duplicates.bai
samtools index KuraCtrl_Input_S14_marked_duplicates.bam KuraCtrl_Input_S14_marked_duplicates.bai
samtools index KuraCtrl_IgG_S13_marked_duplicates.bam KuraCtrl_IgG_S13_marked_duplicates.bai
samtools index KuraCtrl_cJun_S12_marked_duplicates.bam KuraCtrl_cJun_S12_marked_duplicates.bai
samtools index KuraCtrl_H3K9_S11_marked_duplicates.bam KuraCtrl_H3K9_S11_marked_duplicates.bai

# From Deeptools installed using pip
bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/Ctrl_H3K9_S26_marked_duplicates.bam -o Ctrl_H3K9_S26.bw --binSize 10 --scaleFactor 0.0484 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV33D_Input_S25_marked_duplicates.bam -o OV33D_Input_S25.bw --binSize 10 --scaleFactor 0.1611 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV33D_IgG_S24_marked_duplicates.bam -o OV33D_IgG_S24.bw --binSize 10 --scaleFactor 0.2381 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV33D_cJun_S23_marked_duplicates.bam -o OV33D_cJun_S23.bw --binSize 10 --scaleFactor 4.1771 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3Ctrl_Input_S22_marked_duplicates.bam -o OV3Ctrl_Input_S22.bw --binSize 10 --scaleFactor 0.2114 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3Ctrl_IgG_S21_marked_duplicates.bam -o OV3Ctrl_IgG_S21.bw --binSize 10 --scaleFactor 0.6026 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3Ctrl_cJun_S20_marked_duplicates.bam -o OV3Ctrl_cJun_S20.bw --binSize 10 --scaleFactor 1.3947 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3Ctrl_H3K9_S19_marked_duplicates.bam -o OV3Ctrl_H3K9_S19.bw --binSize 10 --scaleFactor 0.7863 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/Kura3D_Input_S18_marked_duplicates.bam -o Kura3D_Input_S18.bw --binSize 10 --scaleFactor 0.2781 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/Kura3D_IgG_S17_marked_duplicates.bam -o Kura3D_IgG_S17.bw --binSize 10 --scaleFactor 0.0474 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/Kura3D_cJun_S16_marked_duplicates.bam -o Kura3D_cJun_S16.bw --binSize 10 --scaleFactor 0.0201 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/Kura3D_H3K9_S15_marked_duplicates.bam -o Kura3D_H3K9_S15.bw --binSize 10 --scaleFactor 0.0559 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/KuraCtrl_Input_S14_marked_duplicates.bam -o KuraCtrl_Input_S14.bw --binSize 10 --scaleFactor 0.2338 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/KuraCtrl_IgG_S13_marked_duplicates.bam -o KuraCtrl_IgG_S13.bw --binSize 10 --scaleFactor 0.0657 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/KuraCtrl_cJun_S12_marked_duplicates.bam -o KuraCtrl_cJun_S12.bw --binSize 10 --scaleFactor 0.0575 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

bamCoverage --bam /N/slate/xuexiao/cJun_CREB1_ChIP/Align/KuraCtrl_H3K9_S11_marked_duplicates.bam -o KuraCtrl_H3K9_S11.bw --binSize 10 --scaleFactor 17.9856 --ignoreForNormalization chrX chrY --extendReads --outFileFormat bigwig

source deactivate





